transition error Fixed in pie-chart.
that line cause error of:
TypeError: undefined is not a function (near '...', click).transition().duration(750).att...') ;
and this is an open issue, so i resolve it!